name: Trigger auto deployment for ecommerceapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/ecommerceapi-AutoDeployTrigger-82b19362-c888-471b-bc3d-e4af02109a81.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ECOMMERCEAPI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: hub.docker.com/repository/docker/rahulkumar2620/ecommerceapi/general
          registryUsername: ${{ secrets.ECOMMERCEAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ECOMMERCEAPI_REGISTRY_PASSWORD }}
          containerAppName: ecommerceapi
          resourceGroup: ecommerce
          imageToBuild: hub.docker.com/repository/docker/rahulkumar2620/ecommerceapi/general/ecommerceapi:${{ github.sha }}
          

     

