name: Docker Image CI

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag my-image-name

  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push to Docker Hub
      run: |
        docker tag e-commerceapi_v1:latest ${{ secrets.DOCKER_HUB_USERNAME }}/e-commerceapi_v1:v1.0
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/e-commerceapi_v1:v1.0
